# Generated by Django 6.0.3 on 2026-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rompecabezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='rompecabezas/')),
                ('dificultad', models.IntegerField(choices=[(3, 'Fácil (3x3)'), (4, 'Medio (4x4)'), (5, 'Difícil (5x5)')], default=3)),
            ],
        ),
    ]
