# Generated by Django 6.0.3 on 2026-05-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginas_leidas', models.IntegerField(default=0)),
                ('fichas_desbloqueadas', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.jugador')),
                ('rompecabezas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.rompecabezas')),
            ],
            options={
                'verbose_name': 'Progreso de Juego',
                'verbose_name_plural': 'Progresos de Juegos',
                'unique_together': {('jugador', 'rompecabezas')},
            },
        ),
    ]
