# Generated by Django 6.0.3 on 2026-05-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_progresojuego'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fichas_ganadas',
            field=models.IntegerField(default=0),
        ),
    ]
