# Generated by Django 6.0.3 on 2026-05-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_jugador_fichas_ganadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('imagen_portada', models.CharField(max_length=200)),
                ('url_lectura', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
