# Generated by Django 6.0.3 on 2026-05-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='imagen_portada',
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cuentos/'),
        ),
    ]
