# Generated by Django 6.0.3 on 2026-05-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_libro_imagen_portada_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rompecabezas',
            name='tipo',
            field=models.CharField(choices=[('RETO', 'Desbloqueo por lectura'), ('LIBRE', 'Modo Libre')], default='LIBRE', max_length=10),
        ),
    ]
