# Generated by Django 6.0.3 on 2026-05-13 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_rompecabezas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rompecabezas',
            name='cuento_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rompecabezas_retos', to='aplicacion.libro'),
        ),
    ]
