# Generated by Django 6.0.3 on 2026-05-20 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_rompecabezas_cuento_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='es_adicional',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaginaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='paginas_cuentos/')),
                ('numero_pagina', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='aplicacion.libro')),
            ],
            options={
                'verbose_name': 'Página de Libro',
                'verbose_name_plural': 'Páginas de Libros',
                'ordering': ['numero_pagina'],
            },
        ),
    ]
