# Generated by Django 6.0.3 on 2026-05-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_libro_es_adicional_paginalibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresojuego',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
