# Generated by Django 6.0.3 on 2026-05-30 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_progresojuego_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAhorcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
                ('tiempo_respuesta', models.FloatField(help_text='Tiempo en segundos')),
                ('intentos', models.IntegerField()),
                ('resultado', models.BooleanField(default=False, help_text='True si ganó, False si perdió')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ahorcado', to='aplicacion.jugador')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.libro')),
            ],
            options={
                'verbose_name': 'Historial de Ahorcado',
                'verbose_name_plural': 'Historiales de Ahorcado',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('paginas_leidas', models.IntegerField(default=0)),
                ('preguntas_totales', models.IntegerField(default=0)),
                ('preguntas_correctas', models.IntegerField(default=0)),
                ('porcentaje_comprension', models.FloatField(default=0.0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_lecturas', to='aplicacion.jugador')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.libro')),
            ],
            options={
                'verbose_name': 'Historial de Lectura',
                'verbose_name_plural': 'Historiales de Lectura',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRompecabezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.IntegerField(choices=[(3, 'Fácil (3x3)'), (4, 'Medio (4x4)'), (5, 'Difícil (5x5)')])),
                ('tiempo_empleado', models.FloatField(help_text='Tiempo en segundos')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_rompecabezas', to='aplicacion.jugador')),
                ('rompecabezas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.rompecabezas')),
            ],
            options={
                'verbose_name': 'Historial de Rompecabezas',
                'verbose_name_plural': 'Historiales de Rompecabezas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTrofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trofeo', models.CharField(choices=[('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro')], max_length=10)),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_trofeos', to='aplicacion.jugador')),
            ],
            options={
                'verbose_name': 'Historial de Trofeo',
                'verbose_name_plural': 'Historiales de Trofeos',
                'ordering': ['-fecha_obtenida'],
            },
        ),
    ]
