# Generated by Django 6.0.3 on 2026-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_historialahorcado_historiallectura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialrompecabezas',
            name='movimientos_correctos',
            field=models.IntegerField(default=0, help_text='Piezas colocadas correctamente'),
        ),
        migrations.AddField(
            model_name='historialrompecabezas',
            name='movimientos_totales',
            field=models.IntegerField(default=0, help_text='Total de movimientos realizados'),
        ),
    ]
