# Generated by Django 6.0.3 on 2026-06-02 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_historialrompecabezas_movimientos_correctos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='es_generado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='moraleja',
            field=models.TextField(blank=True, help_text='Moraleja final editable para libros generados.', null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada_final',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_finales/'),
        ),
        migrations.CreateModel(
            name='AhorcadoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion_activacion', models.IntegerField(help_text='Índice de la sección en la que se activa el ahorcado.')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.CharField(max_length=100)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_ahorcado', to='aplicacion.libro')),
            ],
            options={
                'verbose_name': 'Pregunta de Ahorcado Generado',
                'verbose_name_plural': 'Preguntas de Ahorcado Generado',
                'ordering': ['seccion_activacion'],
            },
        ),
        migrations.CreateModel(
            name='CuentoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='Orden de aparición de la sección.')),
                ('texto', models.TextField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_generadas', to='aplicacion.libro')),
            ],
            options={
                'verbose_name': 'Sección de Cuento',
                'verbose_name_plural': 'Secciones de Cuento',
                'ordering': ['orden'],
            },
        ),
    ]
