# Generated by Django 6.0.3 on 2026-06-06 23:16

import aplicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_libro_es_generado_libro_moraleja_libro_portada_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='codigo_acceso',
            field=models.CharField(default=aplicacion.models.generar_codigo_acceso, max_length=4),
        ),
    ]
